### ISSUE TITLE
[QUESTION] - Connection is auto closed after some time. How to keep the connection alive?

### ISSUE THREAD

**Issue by sujit-baniya** [M2MGateway/go-smpp#13]
It seems the connection is dropped after a minute or two.

Here's a pcap file for the requests

[connection-dropped.zip](https://github.com/M2MGateway/go-smpp/files/6944886/connection-dropped.zip)

How can I make sure the connection is alive until I stop?
Also How can I rebind the connection in case the connection is closed?

Related video: https://storyxpress.co/video/ks0714xl10giqbkct

**Comment by septs** [comment]
https://github.com/M2MGateway/go-smpp/blob/6c6ef183a2dd9e8ff6b928b5127244d9a48b0b7e/cmd/smpp-receiver/main.go#L84-L89

**Comment by septs** [comment]
suggest, yourself implementation connection manage "class", replace my `conn.go` implementation

> If you do not like the default conn.go implementation, you can easily replace it.

from README

**Comment by sujit-baniya** [comment]
@septs Thanks I'll try it. I'm trying to implement multiple session per SMSC along with throttling

**Comment by sujit-baniya** [comment]
@septs I noticed that I could avoid constant rebinding if I set EnquiryInterval (30 sec) lower than EnquiryTimeout (1 min)
