### ISSUE TITLE
SMPP Daemon

### ISSUE THREAD

**Issue by septs** [M2MGateway/go-smpp#6]
Feature set

- [ ] Built-in message queue
- [ ] Built-in SQLite database
- [ ] API Service
   - [ ] HTTP (RESTful)
   - [ ] TCP Server (JSON-RPC)
   - [ ] WebSocket (JSON-RPC)
- [ ] User Script ([lua](https://lua.org) based)
- [ ] Rule-based Router
- [ ] Rule-based Relay
- [ ] SMS-TPDU bridge

**Comment by professor93** [comment]
Is there any news with this issue?

**Comment by septs** [comment]
sorry, this library will not be maintained in the next 6 months.
